### PR TITLE
[wip] Bitcoind support, unified source of chain data

### PR DESCRIPTION
**Pull request by johncantrell97**
Adds support for both bitcoind and electrum backend.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
Is block filter synchronization in scope for this?

**Comment by johncantrell97** [comment]
CBF is not included in this PR but this lays the groundwork to support it going forward.

**Comment by gkrizek** [comment]
Curious if this uses bitcoind's ZMQ interface or only the RPCs? Additionally, does it surface mempool information like when a funding tx just shows up but isn't yet confirmed?

**Comment by johncantrell97** [comment]
circling back here because I was blocked on an issue upstream.  

this does not use zmq at all, it polls for blocks using rpc.  zmq would probably be better for keeping ldk in sync but you still need rpc for initial synchronization at startup.

hm the mempool question is related to bdk -- I'm not actually sure if bdk's sync when using bitcoind pulls mempool tx information

**Comment by gkrizek** [comment]
Makes sense. Yeah, ZMQ doesn't remove the dependency on the RPC. If you aren't worried about mempool then I'd almost recommend sticking to RPC only (like clightning) as it's simpler.

**Comment by johncantrell97** [comment]
makes sense -- i'll probably add ZMQ support later, feels more like a nice-to-have at this point.

after thinking about the most efficient way forward for Sensei I've morphed this PR from "multiple backend support" to "bitcoind support".

I've decided to strip Electrum support and just focus entirely on bitcoind for now.  There are a few reasons:

1. It simplifies the code all over the place to just have one main backend supported.  
2. ldk provides adequate support for bitcoind which will make me feel more confident in a production-ready release of sensei.
3. It's the more efficient solution.  With bitcoind we can poll for new blocks and then propagate the block data to every component that cares.  The amount of bandwidth/data being polled for is constant with respect to the number of nodes.  With an electrum or `Confirm` style implementation the amount of data you are polling for updates scales with the number of nodes.

**Comment by johncantrell97** [comment]
This is blocked upstream until ldk releases 106 with a fix for thread-safe dynamic chain listeners.  It's close to being ready though!

**Pull request merged**
